import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { Providers } from "./providers";
import WalletConnect from "./components/WalletConnect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <header className="page-container flex items-center justify-between">
            <Link
              className="inline-block"
              href="/"
              aria-label="Tiergarten Home"
            >
              <Image
                src="/logo.svg"
                alt="Tiergarten Logo"
                width={102}
                height={131}
              />
              <div className="text-sm text-gray-900 -mt-2">Happy Paws Zoo</div>
            </Link>
            <WalletConnect />
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
